-- MySQL Script generated by MySQL Workbench
-- Tue Apr 28 20:45:44 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `password` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(20) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `balance` DECIMAL(14,2) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_accounts_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_accounts_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account_transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`account_transactions` (
  `id` BIGINT NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  `description` VARCHAR(256) NOT NULL,
  `value` DECIMAL(10,2) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `time` TIME NULL,
  `application` VARCHAR(45) NULL,
  `link` TEXT NULL,
  `accounts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transactions_accounts1_idx` (`accounts_id` ASC) VISIBLE,
  CONSTRAINT `fk_transactions_accounts1`
    FOREIGN KEY (`accounts_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`credit_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`credit_card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastdigits` CHAR(4) NOT NULL,
  `limit` DECIMAL(12,2) NOT NULL,
  `closingdate` DATE NOT NULL,
  `expirationdate` DATE NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_creditcard_banks_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_creditcard_banks0`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`credit_transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`credit_transactions` (
  `id` BIGINT NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  `description` VARCHAR(256) NOT NULL,
  `value` DECIMAL(10,2) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `time` TIME NULL,
  `application` VARCHAR(45) NULL,
  `link` TEXT NULL,
  `installment` INT NULL,
  `credit_card_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_credit_transactions_credit_card1_idx` (`credit_card_id` ASC) VISIBLE,
  CONSTRAINT `fk_credit_transactions_credit_card1`
    FOREIGN KEY (`credit_card_id`)
    REFERENCES `mydb`.`credit_card` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
